version: "3.2"

services:
  api:
    image: rust:latest
    container_name: lite-server
    volumes:
      - .:/app
    working_dir: /app
    command: cargo run
    ports:
      - "80:80"
    environment:
      - DB_PATH=./designations.db